### ISSUE TITLE
Concept

### ISSUE THREAD

**Issue by pkill37** [fedosgad/tcp_mimic#1]
What's the idea here? Catch the ClientHello packets and change them on the wire? Does that work?

The tls client keeps a running hash of the exchanged messages, called the transcript hash, which would detect the changed packet

https://datatracker.ietf.org/doc/html/rfc8446#page-63

**Comment by fedosgad** [comment]
Hello!
You are talking about TLS mimicry, while this repo is about TCP/IP mimicry.
For the former, take a look at https://github.com/fedosgad/mirror_proxy - it is written specifically for TLS.
This repo is about mimicking things like [p0f](https://lcamtuf.coredump.cx/p0f3/) fingerpints. It is more of an experiment for now, so don't rely on it.

**Comment by pkill37** [comment]
Cheers I understand now!

Curious if the code is currently doing anything? It looks like it is a very early demo which is just printing details from packets going through, but nothing is changed?

**Comment by fedosgad** [comment]
Code now is indeed in a demo state.
I have semi-working version on a private branch, but not yet ready to publish it, sorry.
If you are interested in TCP/IP mimicry, take a look at https://github.com/Nisitay/pyp0f/blob/master/examples/impersonate/spoof-p0f.py - it's essentially the Python version of what I want to do.
